### ISSUE TITLE
Cosmetic changes to Settings panel

### ISSUE THREAD

**Issue by alekslovestech** [alekslovestech/chromatic-circle#97]
- [x] Inversion buttons should be a little smaller
- [x] All chord names should fit (see 7add13)
- [x] Interval buttons should be more narrow
- [x] Selected chords / inversions should be visually indicated (currently there's only a hover color)

**Comment by alekslovestech** [comment]
![image](https://github.com/user-attachments/assets/d5b01187-6a66-49b3-a50c-6641f3cac9a1)

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified ChordNameDisplay.tsx and ChordNameDisplay.css to make inversion buttons smaller, ensure all chord names fit, and make interval buttons more narrow.

You can review changes in this commit: https://github.com/lattaai13/alekslovestech-chromatic-circle-97/commit/cf579546290b905e26133157ac139f0597428f5c.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
